### ISSUE TITLE
Does the introduced memory bank for metric loss boost the performance of Person Re-ID?

### ISSUE THREAD

**Issue by hfutzzw** [Xiangyu-CAS/Yet-Another-reid-baseline#1]

**Comment by Xiangyu-CAS** [comment]
Memory bank is quite unstable on Person ReID, most of the time, it brings no gain and no drop, but sometime it lead to minor increment . 
Actually, metric learning contributes at most 1% performance in my experiments. So it's no wonder memory bank doesn't affect much.

**Comment by hfutzzw** [comment]
ok, thank you! According to the original XBM paper, the memory bank improved the performance significantly in vehicle-ReID and 
general image retrieval task,  may be 16x4 batchsize for hard example mining in  person Re-ID is good enough.
