### ISSUE TITLE
spgan

### ISSUE THREAD

**Issue by bixiaopeng0** [Xiangyu-CAS/Yet-Another-reid-baseline#2]
大佬，使用spgan方法转换pensonx数据那部分代码实现在哪呀，我没找到

**Comment by Xiangyu-CAS** [comment]
您好，personx_spgan是直接从比赛方spgan作者那里获取的，[VisDA2020](https://github.com/Simon4Yan/VisDA2020), [download link](https://onedrive.live.com/redir?resid=A0439A5E6C1EEB18!108&authkey=!AIahEx1m49NDuDI&e=i9wE31)

**Comment by bixiaopeng0** [comment]
哦哦，晓得了，谢谢大佬。
